"""Service method invocation screen.

Covers the read/delete methods generated by ServiceFactory:

- ``get_list(options=None)`` - supports the full set of query options
- ``get_by_id(entity_id)`` - single record
- ``get_by_keys(**key_fields)`` - single record by arbitrary keys
- ``get_ad_hoc_schema()`` - metadata only, no params
- ``get_files(entity_id)`` - file attachments for one record
- ``delete_by_id(entity_id)`` - destructive, requires confirmation
- ``delete_by_keys(**key_fields)`` - destructive, requires confirmation

Only ``get_list`` shows the query-option inputs (the single-record fetches
and destructive calls don't use them here). Destructive methods require
pressing Execute twice - the first press shows a warning in the status bar.
The call runs on a worker thread; the result renders as pretty JSON.
"""
from __future__ import annotations

import json
import rich.markup
from typing import Any, Dict, List, Optional, Tuple

from textual.app import ComposeResult
from textual.binding import Binding
from textual.containers import Container, Horizontal, VerticalScroll
from textual.screen import Screen
from textual.widgets import (
    Button,
    Footer,
    Input,
    Label,
    Static,
)
from textual.worker import Worker, WorkerState


# --- Constants ------------------------------------------------------------

METHODS = (
    'get_list',
    'get_by_id',
    'get_by_keys',
    'get_ad_hoc_schema',
    'get_files',
    'put_entity',
    'put_file',
    'delete_by_id',
    'delete_by_keys',
)

METHOD_DESCRIPTIONS = {
    'get_list': 'Fetch a list of records. Supports the full query options.',
    'get_by_id': 'Fetch one record by its primary key (path segment).',
    'get_by_keys': 'Fetch one record by arbitrary key fields (path segments).',
    'get_ad_hoc_schema': 'Fetch the ad-hoc schema metadata. No params.',
    'get_files': 'List file attachments for one record (by primary key).',
    'put_entity': '[yellow]WRITES[/yellow] - create or update a record. Build the entity first.',
    'put_file': '[yellow]WRITES[/yellow] - attach a local file to a record by primary key.',
    'delete_by_id': '[red]DESTRUCTIVE[/red] - delete one record by its primary key.',
    'delete_by_keys': '[red]DESTRUCTIVE[/red] - delete one record by key fields.',
}

# Only get_list meaningfully uses query options in this UI.
METHODS_WITH_OPTIONS = {'get_list'}

# Destructive methods require a second Execute press to confirm.
DESTRUCTIVE_METHODS = {'delete_by_id', 'delete_by_keys'}

# Methods whose form has no plain-text params (the entity is built in a
# nested screen, the file is read from disk).
SPECIAL_FORM_METHODS = {'put_entity', 'put_file'}

OPTION_FIELDS = (
    ('top', '$top', 'Limit rows (e.g. 10)'),
    ('skip', '$skip', 'Skip rows (pagination offset)'),
    ('select', '$select', 'Comma-separated field list'),
    ('expand', '$expand', 'Comma-separated expand list'),
    ('orderby', '$orderby', 'Sort field(s), e.g. "Name desc"'),
    ('filter', '$filter', "F.Name == 'foo' - F syntax or raw OData"),
)


# --- Helpers --------------------------------------------------------------


def _available_methods(service: Any) -> List[str]:
    """Return the subset of METHODS that actually exist on the service."""
    return [m for m in METHODS if callable(getattr(service, m, None))]


def _split_list(raw: str) -> Optional[List[str]]:
    """Parse a comma-separated input into a list, or None if empty."""
    parts = [p.strip() for p in raw.split(',') if p.strip()]
    return parts or None


def _parse_int(raw: str) -> Optional[int]:
    raw = raw.strip()
    if not raw:
        return None
    return int(raw)


def _parse_filter(raw: str):
    """
    Parse a filter input.

    Preference: evaluate as a Python F-expression (e.g. ``F.Name == 'foo'``
    or ``(F.Status == 'Active') & (F.Amount > 50)``). If evaluation fails,
    or the result isn't a Filter instance, fall back to passing the raw
    string through as a literal OData filter (e.g. ``Name eq 'foo'``).

    Returns None for empty input.
    """
    from easy_acumatica.odata import F, Filter

    raw = raw.strip()
    if not raw:
        return None

    try:
        # Sandbox: no builtins, only F in scope. Safe enough for a dev tool -
        # the user is typing into their own debug session.
        result = eval(raw, {'__builtins__': {}}, {'F': F})
    except Exception:
        return raw

    if isinstance(result, Filter):
        return result
    # Expression evaluated to something unexpected (e.g. int, bool) - treat
    # it as raw text so the user sees a real server-side error rather than
    # silently passing junk.
    return raw


def _build_query_options(form: Dict[str, str]):
    """
    Build a QueryOptions from form input. Returns None if everything is empty
    (so we pass options=None rather than an empty container).

    Raises ValueError for bad numeric input (caller surfaces the message).
    """
    from easy_acumatica.odata import QueryOptions

    top = _parse_int(form.get('top', ''))
    skip = _parse_int(form.get('skip', ''))
    select = _split_list(form.get('select', ''))
    expand = _split_list(form.get('expand', ''))
    orderby_raw = form.get('orderby', '').strip()
    orderby = _split_list(orderby_raw) if ',' in orderby_raw else (orderby_raw or None)
    filter_value = _parse_filter(form.get('filter', ''))

    if all(v is None for v in (top, skip, select, expand, orderby, filter_value)):
        return None

    return QueryOptions(
        top=top,
        skip=skip,
        select=select,
        expand=expand,
        orderby=orderby,
        filter=filter_value,
    )


# --- Screen ---------------------------------------------------------------


class ServiceCallScreen(Screen):
    """Form + result pane for invoking a method on a service."""

    BINDINGS = [
        Binding('escape', 'back', 'Back'),
        Binding('ctrl+enter', 'execute', 'Execute', show=True, key_display='Ctrl+Enter'),
    ]

    def __init__(
        self,
        service_name: str,
        inquiry_method: Optional[str] = None,
    ) -> None:
        super().__init__()
        self._service_name = service_name
        # When set, the screen is rendering a single Generic Inquiry rather
        # than a regular service. The inquiry method behaves like get_list
        # for UI purposes (QueryOptions only, JSON result, no destructive
        # confirmation, no model builder).
        self._inquiry_method: Optional[str] = inquiry_method
        self._is_inquiry: bool = inquiry_method is not None
        self._service: Any = None
        self._method_name: str = inquiry_method or 'get_list'
        self._key_rows: int = 1  # for get_by_keys / delete_by_keys
        self._last_result: Any = None
        # Destructive methods require a second Execute press to confirm.
        # The flag is flipped on the first press and reset on any state
        # change (method switch, successful call, navigation away).
        self._confirmed_destructive: bool = False
        # put_entity: the model instance built in the nested ModelBuilderScreen.
        self._built_entity: Any = None
        # Cache of the current rendered code snippet (so the Copy button
        # has something to send to the clipboard regardless of focus).
        self._last_preview: str = ""

    # -- Compose ---------------------------------------------------------

    def compose(self) -> ComposeResult:
        with VerticalScroll(id='call-root'):
            if self._is_inquiry:
                title = f'Call inquiry: [b]{self._inquiry_method}[/b]'
            else:
                title = f'Call service: [b]{self._service_name}[/b]'
            yield Static(title, id='call-title', markup=True)

            yield Label('Method')
            # Button row is populated in _post_mount_setup with the subset
            # of GET methods the service actually exposes. Using plain
            # Buttons (rather than a RadioSet) keeps selection state simple:
            # the active button gets the `.active` class; clicking switches.
            yield Horizontal(id='method-set')
            yield Static('', id='method-description', markup=True)

            # Method-specific inputs live inside this container; contents are
            # swapped whenever the selected method changes.
            yield Container(id='method-params')

            yield Static('Query Options', id='options-title')
            with Container(id='options-grid'):
                for field_key, display, placeholder in OPTION_FIELDS:
                    yield Label(display)
                    yield Input(placeholder=placeholder, id=f'opt-{field_key}')

            with Horizontal(id='call-buttons'):
                yield Button('Back', id='back')
                yield Button('Copy code', id='copy-code')
                yield Button('Execute', id='execute', variant='primary')

            yield Static('', id='call-status', markup=True)

            yield Static('Equivalent Python', id='code-preview-title')
            yield Static('', id='code-preview', markup=False)

            yield Static('Result', id='result-title')
            yield Static('(no result yet)', id='result-pane')
        yield Footer()

    # -- Mount / lookup --------------------------------------------------

    def on_mount(self) -> None:
        # Resolve the service up front - no DOM access yet.
        client = getattr(self.app, 'client', None)
        if client is not None:
            self._service = client._service_instances.get(self._service_name)
        # Children aren't mounted yet at on_mount time; defer DOM work.
        self.call_after_refresh(self._post_mount_setup)

    async def _post_mount_setup(self) -> None:
        if self._service is None:
            client = getattr(self.app, 'client', None)
            if client is None:
                self._set_status('No active client.')
            else:
                self._set_status(
                    f'Service "{self._service_name}" not found on client.'
                )
            return

        if self._is_inquiry:
            # Inquiry mode: there's exactly one "method" (the inquiry itself)
            # and no method-selection row. The label/description is rendered
            # in the description Static.
            method = self._inquiry_method or ''
            if not callable(getattr(self._service, method, None)):
                self._set_status(
                    f'Inquiry "{method}" not found on Inquiries service.'
                )
                return
            # Hide the empty method-set container.
            try:
                self.query_one('#method-set', Horizontal).display = False
            except Exception:
                pass
            self._method_name = method
            self._render_method_params()
            self._render_method_description()
            self._sync_options_visibility()
            self._render_preview()
            return

        available = _available_methods(self._service)
        if not available:
            self._set_status(
                f'Service "{self._service_name}" exposes no callable methods.'
            )
            return

        # Populate the method row with only the methods the service exposes.
        # This hides unavailable methods entirely (no disabled buttons).
        row = self.query_one('#method-set', Horizontal)
        for i, name in enumerate(available):
            await row.mount(Button(
                name,
                id=f'm-{name}',
                classes='active' if i == 0 else '',
            ))

        self._method_name = available[0]
        self._render_method_params()
        self._render_method_description()
        self._sync_options_visibility()
        self._render_preview()

    # -- Events ----------------------------------------------------------

    def _select_method(self, name: str) -> None:
        """Activate a method button: update state, visuals, and form."""
        if name == self._method_name:
            return
        self._method_name = name
        self._confirmed_destructive = False  # switching methods resets confirm
        # Reset put_entity state when leaving (fresh build per session).
        if name != 'put_entity':
            self._built_entity = None
        row = self.query_one('#method-set', Horizontal)
        for button in row.query(Button):
            button.set_class(button.id == f'm-{name}', 'active')
        self._render_method_params()
        self._render_method_description()
        self._sync_options_visibility()
        self._set_status('')  # clear any stale confirmation prompt
        self._render_preview()

    def _sync_options_visibility(self) -> None:
        """Show the options grid only for methods that use query options."""
        title = self.query_one('#options-title', Static)
        grid = self.query_one('#options-grid', Container)
        visible = self._is_inquiry or self._method_name in METHODS_WITH_OPTIONS
        title.display = visible
        grid.display = visible

    def on_button_pressed(self, event: Button.Pressed) -> None:
        bid = event.button.id or ''
        if bid == 'back':
            self.app.pop_screen()
        elif bid == 'execute':
            self.action_execute()
        elif bid == 'copy-code':
            self._copy_preview()
        elif bid == 'build-entity':
            self._open_entity_builder()
        elif bid == 'add-key':
            self._key_rows += 1
            self._render_method_params()
        elif bid.startswith('m-'):
            self._select_method(bid.removeprefix('m-'))

    def on_input_changed(self, event: Input.Changed) -> None:
        """Re-render the code preview as the user edits inputs."""
        self._render_preview()

    # -- put_entity: open the model builder ------------------------------

    def _open_entity_builder(self) -> None:
        entity_class = self._resolve_entity_model_class()
        if entity_class is None:
            self._set_status(
                f'[red]No model class found for {self._service_name!r}.[/red]'
            )
            return

        from .model_builder import ModelBuilderScreen

        def _on_built(result):
            if result is None:
                return
            self._built_entity = result
            try:
                self.query_one('#entity-status', Static).update(
                    f'[green][configured: {type(result).__name__}][/green]'
                )
            except Exception:
                pass
            self._render_preview()

        self.app.push_screen(ModelBuilderScreen(entity_class), _on_built)

    # -- Copy code -------------------------------------------------------

    def _copy_preview(self) -> None:
        """Send the current code preview to the system clipboard."""
        if not self._last_preview:
            self._set_status('[yellow]Nothing to copy yet.[/yellow]')
            return
        try:
            self.app.copy_to_clipboard(self._last_preview)
        except Exception as e:
            self._set_status(f'[red]Copy failed: {e}[/red]')
            return
        self._set_status('[green]Copied to clipboard.[/green]')

    # -- Dynamic method-param rendering ----------------------------------

    def _render_method_description(self) -> None:
        if self._is_inquiry:
            doc = (getattr(self._service, self._method_name, None).__doc__ or '').strip()
            summary = doc.splitlines()[0] if doc else 'Generic Inquiry. Supports the full query options.'
            desc = summary
        else:
            desc = METHOD_DESCRIPTIONS.get(self._method_name, '')
        self.query_one('#method-description', Static).update(f'[dim]{desc}[/dim]')

    def _render_method_params(self) -> None:
        """Schedule a rebuild of the method-specific input widgets."""
        self.call_after_refresh(self._rebuild_method_params)

    async def _rebuild_method_params(self) -> None:
        """
        Rebuild method-specific inputs. Runs on the UI event loop so
        ``remove_children()`` can be awaited - mounting new widgets
        before removal completes produces duplicate-ID errors.
        """
        container = self.query_one('#method-params', Container)
        await container.remove_children()

        if self._method_name in ('get_by_id', 'delete_by_id', 'get_files'):
            await container.mount(Label('Entity ID - Acumatica GUID (required)'))
            await container.mount(Input(
                placeholder='e.g. a38c9560-913d-f111-8431-126ad4ca5ceb',
                id='p-entity-id',
            ))

        elif self._method_name in ('get_by_keys', 'delete_by_keys'):
            await container.mount(Label('Key fields (name=value per row)'))
            for i in range(self._key_rows):
                await container.mount(Horizontal(
                    Input(placeholder='key name', id=f'k-name-{i}', classes='key-name'),
                    Input(placeholder='value', id=f'k-value-{i}', classes='key-value'),
                    classes='key-row',
                ))
            await container.mount(Button('+ Add key field', id='add-key', variant='default'))

        elif self._method_name == 'put_entity':
            entity_class = self._resolve_entity_model_class()
            label = (
                f'Entity: {entity_class.__name__}'
                if entity_class is not None
                else f'Entity model not found for {self._service_name}'
            )
            await container.mount(Label(label))
            status = (
                f'[green][configured: {type(self._built_entity).__name__}][/green]'
                if self._built_entity is not None
                else '[dim][not set][/dim]'
            )
            await container.mount(Horizontal(
                Button(
                    f'Build {entity_class.__name__}' if entity_class else 'Build entity',
                    id='build-entity',
                    disabled=entity_class is None,
                ),
                Static(status, id='entity-status', markup=True),
                classes='nested-row',
            ))

        elif self._method_name == 'put_file':
            await container.mount(Label('Entity ID - Acumatica GUID (required)'))
            await container.mount(Input(
                placeholder='e.g. a38c9560-913d-f111-8431-126ad4ca5ceb',
                id='p-entity-id',
            ))
            await container.mount(Label('Local file path (required)'))
            await container.mount(Input(
                placeholder='C:\\path\\to\\file.pdf',
                id='p-file-path',
            ))
            await container.mount(Label('Filename on server (optional, defaults to basename)'))
            await container.mount(Input(
                placeholder='attachment.pdf',
                id='p-filename',
            ))
            await container.mount(Label('Comment (optional)'))
            await container.mount(Input(
                placeholder='cover sheet',
                id='p-comment',
            ))

        # get_list / get_ad_hoc_schema: no method-specific params
        container.refresh(layout=True)
        # Refresh the preview now that the form has changed.
        self.call_after_refresh(self._render_preview)

    def _resolve_entity_model_class(self) -> Optional[type]:
        """Find the dataclass that this service's put_entity expects.

        Look up by service.entity_name on the client.models module.
        Returns None when no matching model exists.
        """
        client = getattr(self.app, 'client', None)
        if client is None or self._service is None:
            return None
        entity_name = getattr(self._service, 'entity_name', None)
        if not entity_name:
            return None
        return getattr(getattr(client, 'models', None), entity_name, None)

    # -- Execute --------------------------------------------------------

    def action_back(self) -> None:
        self.app.pop_screen()

    def action_execute(self) -> None:
        # Validate arguments BEFORE the confirmation prompt so the user
        # doesn't have to press Execute twice and then discover a typo.
        try:
            args, kwargs = self._collect_call_args()
        except ValueError as e:
            self._set_status(f'[red]Invalid input: {e}[/red]')
            return

        # Destructive methods: require a second Execute press to confirm.
        if self._method_name in DESTRUCTIVE_METHODS and not self._confirmed_destructive:
            self._confirmed_destructive = True
            target = args[0] if args else ', '.join(f'{k}={v!r}' for k, v in kwargs.items())
            self._set_status(
                f'[yellow]! DESTRUCTIVE {self._method_name} on '
                f'{self._service_name} ({target}) - press Execute again to confirm.[/yellow]'
            )
            return

        # Confirmed (or non-destructive) - reset flag so the NEXT destructive
        # execute still requires a fresh two-press confirmation.
        self._confirmed_destructive = False
        self._set_status('Running...')
        self.query_one('#result-pane', Static).update('...')
        self._pending_call = (self._method_name, args, kwargs)
        # exit_on_error=False: a failed request (bad filter, 500 response,
        # timeout, etc.) surfaces through on_worker_state_changed instead
        # of tearing down the whole TUI.
        self.run_worker(
            self._execute_call,
            thread=True,
            exclusive=True,
            name='service-call',
            exit_on_error=False,
        )

    def _collect_call_args(self) -> Tuple[List[Any], Dict[str, Any]]:
        """Build positional and keyword args for the chosen method."""
        if self._method_name == 'get_list' or self._is_inquiry:
            form = {
                key: self.query_one(f'#opt-{key}', Input).value
                for key, _, _ in OPTION_FIELDS
            }
            options = _build_query_options(form)  # may raise ValueError
            return [], ({'options': options} if options is not None else {})

        # Methods that take a single entity_id as a positional arg.
        if self._method_name in ('get_by_id', 'delete_by_id', 'get_files'):
            entity_id = self.query_one('#p-entity-id', Input).value.strip()
            if not entity_id:
                raise ValueError(
                    f'Entity ID is required for {self._method_name}.'
                )
            return [entity_id], {}

        # Methods that take arbitrary **key_fields.
        if self._method_name in ('get_by_keys', 'delete_by_keys'):
            key_fields: Dict[str, Any] = {}
            for i in range(self._key_rows):
                name = self.query_one(f'#k-name-{i}', Input).value.strip()
                value = self.query_one(f'#k-value-{i}', Input).value.strip()
                if name:
                    key_fields[name] = value
            if not key_fields:
                raise ValueError(
                    f'At least one key field is required for {self._method_name}.'
                )
            return [], key_fields

        if self._method_name == 'get_ad_hoc_schema':
            return [], {}

        if self._method_name == 'put_entity':
            if self._built_entity is None:
                raise ValueError(
                    'Build the entity first (press the Build button).'
                )
            return [self._built_entity], {}

        if self._method_name == 'put_file':
            entity_id = self.query_one('#p-entity-id', Input).value.strip()
            file_path = self.query_one('#p-file-path', Input).value.strip()
            filename = self.query_one('#p-filename', Input).value.strip()
            comment = self.query_one('#p-comment', Input).value.strip()
            if not entity_id:
                raise ValueError('Entity ID is required for put_file.')
            if not file_path:
                raise ValueError('File path is required for put_file.')
            try:
                with open(file_path, 'rb') as f:
                    data = f.read()
            except OSError as e:
                raise ValueError(f'Cannot read file: {e}')
            if not filename:
                import os
                filename = os.path.basename(file_path)
            kwargs: Dict[str, Any] = {}
            if comment:
                kwargs['comment'] = comment
            return [entity_id, filename, data], kwargs

        raise ValueError(f'Unknown method: {self._method_name}')

    def _execute_call(self) -> Any:
        """Runs on a worker thread."""
        method_name, args, kwargs = self._pending_call
        method = getattr(self._service, method_name)
        return method(*args, **kwargs)

    # -- Worker completion ----------------------------------------------

    def on_worker_state_changed(self, event: Worker.StateChanged) -> None:
        if event.worker.name != 'service-call':
            return
        if event.state == WorkerState.SUCCESS:
            self._last_result = event.worker.result
            self._render_result(self._last_result)
            self._set_status('[green]OK[/green]')
        elif event.state == WorkerState.ERROR:
            err = event.worker.error
            self._render_error(err)

    def _render_error(self, err: Optional[BaseException]) -> None:
        """Show a failed call without crashing the TUI."""
        if err is None:
            self._set_status('[red]Call failed (no error info)[/red]')
            self.query_one('#result-pane', Static).update('(unknown error)')
            return

        type_name = type(err).__name__
        # First line of the exception message for the status bar.
        msg = str(err).strip().splitlines()[0] if str(err).strip() else '(no message)'
        if len(msg) > 120:
            msg = msg[:117] + '...'
        self._set_status(f'[red]{type_name}: {msg}[/red]')

        # Full details in the result pane - escape any markup in the error
        # text so '[' and ']' don't get interpreted by Rich.
        pretty = f'{type_name}: {err}'
        suggestions = getattr(err, 'suggestions', None)
        if suggestions:
            pretty += '\n\nSuggestions:\n' + '\n'.join(
                f'  - {s}' for s in suggestions
            )
        self.query_one('#result-pane', Static).update(
            rich.markup.escape(pretty)
        )

    # -- Output ----------------------------------------------------------

    def _render_result(self, result: Any) -> None:
        pane = self.query_one('#result-pane', Static)
        try:
            pretty = json.dumps(result, indent=2, default=str)
        except (TypeError, ValueError):
            pretty = repr(result)
        if len(pretty) > 20000:
            pretty = pretty[:20000] + '\n... (truncated at 20 KB) ...'
        pane.update(pretty)

    def _set_status(self, message: str) -> None:
        self.query_one('#call-status', Static).update(message)

    # -- Code preview ---------------------------------------------------

    def _client_attr_for_service(self) -> str:
        """The attribute name on the AcumaticaClient that points at this service.

        Service factory derives client.<attr> via to_snake_case(entity_name),
        so we mirror that.
        """
        if self._is_inquiry:
            return 'inquiries'
        from ..service_factory import to_snake_case
        return to_snake_case(self._service_name)

    def _render_preview(self) -> None:
        """Re-render the equivalent-Python preview from the current form state.

        Designed to be cheap and silent on partial/invalid input - this
        runs on every Input change. Validation errors are swallowed; the
        preview just shows whatever was successfully assembled.
        """
        try:
            preview = self._build_preview()
        except Exception:
            preview = ''
        self._last_preview = preview
        try:
            self.query_one('#code-preview', Static).update(preview)
        except Exception:
            pass

    def _build_preview(self) -> str:
        from .code_render import render_call

        client_attr = self._client_attr_for_service()
        method = self._method_name

        # Reconstruct args without raising on partial state.
        positional: List[Any] = []
        keyword: Dict[str, Any] = {}
        entity_model = None

        if method == 'get_list' or self._is_inquiry:
            try:
                form = {
                    key: self.query_one(f'#opt-{key}', Input).value
                    for key, _, _ in OPTION_FIELDS
                }
                opts = _build_query_options(form)
            except Exception:
                opts = None
            if opts is not None:
                keyword['options'] = opts

        elif method in ('get_by_id', 'delete_by_id', 'get_files'):
            try:
                eid = self.query_one('#p-entity-id', Input).value.strip()
                if eid:
                    positional.append(eid)
            except Exception:
                pass

        elif method in ('get_by_keys', 'delete_by_keys'):
            for i in range(self._key_rows):
                try:
                    name = self.query_one(f'#k-name-{i}', Input).value.strip()
                    val = self.query_one(f'#k-value-{i}', Input).value.strip()
                except Exception:
                    continue
                if name:
                    keyword[name] = val

        elif method == 'put_entity':
            entity_model = self._built_entity

        elif method == 'put_file':
            # put_file needs special rendering because the `data` arg is the
            # file's bytes, which we can't (and don't want to) inline. The
            # snippet shows `open(path, 'rb').read()` instead so it's still
            # runnable when pasted.
            return self._render_put_file_preview(client_attr)

        # get_ad_hoc_schema: no args needed - falls through with empty lists.

        return render_call(
            client_attr,
            method,
            positional=positional,
            keyword=keyword,
            entity_model=entity_model,
        )

    def _render_put_file_preview(self, client_attr: str) -> str:
        """Build the put_file snippet directly so the data arg renders as
        ``open(path, 'rb').read()`` rather than a giant bytes literal."""
        try:
            eid = self.query_one('#p-entity-id', Input).value.strip()
            fp = self.query_one('#p-file-path', Input).value.strip()
            fn = self.query_one('#p-filename', Input).value.strip()
            comment = self.query_one('#p-comment', Input).value.strip()
        except Exception:
            return ''

        if not fn and fp:
            import os
            fn = os.path.basename(fp)

        parts: List[str] = []
        parts.append(repr(eid) if eid else "''")
        parts.append(repr(fn) if fn else "''")
        parts.append(f"open({fp!r}, 'rb').read()" if fp else "b''")
        if comment:
            parts.append(f"comment={comment!r}")

        return (
            "from easy_acumatica import AcumaticaClient\n"
            "\n"
            "client = AcumaticaClient()\n"
            "\n"
            f"client.{client_attr}.put_file({', '.join(parts)})"
        )
